#Docker compose para el desarrollo de la aplicación
services:
  node-app:
    build:
      context: .
      dockerfile: dockerfile.dev #Dockerfile para desarrollo
    working_dir: /home/node/nest
    environment:
      - ARCHIVO_ENV=.develop
    volumes:
      - ./:/home/node/nest    
    ports:
      - "4000:5000"
    command: npm run start:dev
    