#Docker compose para el desarrollo de la aplicación
services:
  node-app:
    image: ${NODE_APP_IMAGE}
    environment:
      - ARCHIVO_ENV=.env
    volumes:
      - ./:/home/node/nest
    ports:
      - '${NODE_APP_PORT}:${NODE_APP_CONTAINER_PORT}'
    command: npm run start:dev
    

  bd-server:
    image: ${MYSQL_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    volumes:
      - ./bd-server/sql:/var/lib/mysql
    ports:
      - '${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}'
    
