#Docker compose para el desarrollo de la aplicación
services:
  node-app:
    image: ${NODE_APP_IMAGE}
    env_file:
      - .env
    user: node
    working_dir: /home/node/nest
    environment:
      
      - USER_DBI=${USER_DB}
      - MYSQL_PORT=${MYSQL_HOST_PORT}
      - HOST_DB=${HOST_DB}
      - NAME_DB=${NAME_DB}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - NODE_ENV=development
      
    volumes:
      - ./:/home/node/nest
    ports:
      # - '${NODE_APP_PORT}:${NODE_APP_CONTAINER_PORT}'
    - '4000:5000'
    command: npm run start:dev  

  bd-server:
    image: ${MYSQL_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    volumes:
      - ./bd-server/sql:/var/lib/mysql
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ./BBDD:/flyway/sql
    command: -url=jdbc:mysql://${HOST_DB}:${MYSQL_CONTAINER_PORT}/${NAME_DB}?allowPublicKeyRetrieval=true -user=root -password=${MYSQL_ROOT_PASSWORD} -connectRetries=60 migrate
    
