#Dockerfile para desarrollo
FROM node:22-alpine3.19

RUN mkdir /home/node/nest/ && chown -R node:node /home/node/nest

COPY package.json /home/node/nest/package.json

COPY .env.develop /home/node/nest/.env.develop

WORKDIR /home/node/nest

RUN npm install

COPY . /home/node/nest

CMD [ "npm", "run", "start:dev" ]