#Docker compose para el desarrollo de la aplicación
services:
  node-app:
    image: suescun85/grupo4-backend:v-002
    environment:
      - ARCHIVO_ENV=.develop
    volumes:
      - ./:/home/node/nest
    ports:
      - '4000:5000'
    command: npm run start:dev

  bd-server:
    image: mysql:8.0.39-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
    volumes:
      - ./bd-server/sql:/var/lib/mysql
    ports:
      - '3700:3306'